PYTHON ?= python3
STREAMLIT_RUN = $(PYTHON) -m streamlit run src/app/streamlit_app.py
UI_PORT ?= 8511

.PHONY: listings tickers clean market rwa metrics audit archive db lark ui ui-local ui-lan pipeline daily all

listings:
	$(PYTHON) src/ingestion/hl_listing_monitor.py snapshot --venue all

tickers:
	$(PYTHON) src/ingestion/fetch_venue_ticker_metrics.py

clean:
	$(PYTHON) src/transform/clean_watchboard.py

market:
	$(PYTHON) src/transform/enrich_watchboard_coingecko.py

rwa:
	$(PYTHON) src/transform/label_rwa_tokens.py

metrics:
	@echo "Token metrics and leaderboard marts are generated by the market step; RWA labels are generated by the rwa step."

audit:
	$(PYTHON) src/quality/audit_watchboard_quality.py

archive:
	$(PYTHON) src/transform/archive_daily_snapshot.py --overwrite

db:
	$(PYTHON) src/transform/build_history_store.py

lark:
	$(PYTHON) src/delivery/lark_listing_watchboard.py

ui:
	$(MAKE) ui-local

ui-local:
	$(STREAMLIT_RUN) --server.headless=true --server.address=127.0.0.1 --server.port=$(UI_PORT)

ui-lan:
	$(STREAMLIT_RUN) --server.headless=true --server.address=0.0.0.0 --server.port=$(UI_PORT)

pipeline:
	$(MAKE) clean
	$(MAKE) market
	$(MAKE) rwa
	$(MAKE) tickers
	$(MAKE) metrics
	$(MAKE) audit
	$(MAKE) archive
	$(MAKE) db

daily:
	$(MAKE) pipeline
	$(MAKE) lark

all:
	$(MAKE) listings
	$(MAKE) pipeline
