PYTHON ?= python3
STREAMLIT ?= streamlit

.PHONY: listings tickers clean market metrics audit archive db lark ui ui-lan pipeline daily all

listings:
	$(PYTHON) src/ingestion/hl_listing_monitor.py snapshot --venue all

tickers:
	$(PYTHON) src/ingestion/fetch_venue_ticker_metrics.py

clean:
	$(PYTHON) src/transform/clean_watchboard.py

market:
	$(PYTHON) src/transform/enrich_watchboard_coingecko.py

metrics:
	@echo "Token metrics and leaderboard marts are generated by the market step."

audit:
	$(PYTHON) src/quality/audit_watchboard_quality.py

archive:
	$(PYTHON) src/transform/archive_daily_snapshot.py --overwrite

db:
	$(PYTHON) src/transform/build_history_store.py

lark:
	$(PYTHON) src/delivery/lark_listing_watchboard.py

ui:
	$(STREAMLIT) run src/app/streamlit_app.py

ui-lan:
	$(STREAMLIT) run src/app/streamlit_app.py --server.address=0.0.0.0 --server.port=8511

pipeline:
	$(MAKE) clean
	$(MAKE) market
	$(MAKE) tickers
	$(MAKE) metrics
	$(MAKE) audit
	$(MAKE) archive
	$(MAKE) db

daily:
	$(MAKE) pipeline
	$(MAKE) lark

all:
	$(MAKE) listings
	$(MAKE) pipeline
